trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # You can change this to use your self-hosted agent pool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Use .NET 8 SDK

- task: DotNetCoreCLI@2  # Replaced the Restore task with DotNetCoreCLI
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2  # Replaced the Build task with DotNetCoreCLI
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2  # Replaced the Pack task with DotNetCoreCLI
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    includeSource: true
    includeSymbols: true
    outputDir: '$(Build.ArtifactStagingDirectory)/nuget'

- task: NuGetCommand@2  # Push task is still the same
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nuget/*.nupkg'
    nuGetFeedType: 'internal'
    publishFeed: 'your-azure-artifacts-feed-name'  # Replace with your actual feed name

- task: DotNetCoreCLI@2  # Restore task for NuGet packages
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '69e6b92-xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx'  # Replace with your actual feed ID
